_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
agent_0:
    value: RegretMatching
agent_1:
    value: RegretMatching
game:
    value: Blotto
